
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'const_AES.ucf'
####################################################################################

# -------------------------------------------------------------------------
# Pin assignment of Kintex-7 on SASEBO-GIII
# 
# File name   : pin_sasebo_giii_k7.v
# Version     : 1.1
# Created     : APR/02/2012
# Last update : APR/25/2013
# Desgined by : Toshihiro Katashita
# 
# 
# Copyright (C) 2012, 2013 AIST
# 
# By using this code, you agree to the following terms and conditions.
# 
# This code is copyrighted by AIST ("us").
# 
# Permission is hereby granted to copy, reproduce, redistribute or
# otherwise use this code as long as: there is no monetary profit gained
# specifically from the use or reproduction of this code, it is not sold,
# rented, traded or otherwise marketed, and this copyright notice is
# included prominently in any copy made.
# 
# We shall not be liable for any damages, including without limitation
# direct, indirect, incidental, special or consequential damages arising
# from the use of this code.
# 
# When you publish any results arising from the use of this code, we will
# appreciate it if you can cite our webpage.
# (http://www.risec.aist.go.jp/project/sasebo/)
# -------------------------------------------------------------------------

#================================================?Timing constraint

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:34
create_clock -name lbus_clkn -period 41.666 [get_ports lbus_clkn]


#================================================ Pin assignment
#------------------------------------------------ Clock, reset, LED, and SW.
#################
# CLOCK / RESET #
#################
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:42
set_false_path -through [get_nets osc_en_b]
set_property PACKAGE_PIN J8 [get_ports osc_en_b]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:42
# The conversion of 'IOSTANDARD' constraint on 'net' object 'osc_en_b' has been applied to the port object 'osc_en_b'.
set_property IOSTANDARD LVCMOS25 [get_ports osc_en_b]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:42
# The conversion of 'DRIVE' constraint on 'net' object 'osc_en_b' has been applied to the port object 'osc_en_b'.
set_property DRIVE 2 [get_ports osc_en_b]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:42
# The conversion of 'SLEW' constraint on 'net' object 'osc_en_b' has been applied to the port object 'osc_en_b'.
set_property SLEW QUIETIO [get_ports osc_en_b]

#######
# LED #
#######
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:47
set_false_path -through [get_nets {led[9]}]
set_property PACKAGE_PIN G20 [get_ports {led[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:47
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[9]' has been applied to the port object 'led[9]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:47
# The conversion of 'DRIVE' constraint on 'net' object 'led[9]' has been applied to the port object 'led[9]'.
set_property DRIVE 2 [get_ports {led[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:47
# The conversion of 'SLEW' constraint on 'net' object 'led[9]' has been applied to the port object 'led[9]'.
set_property SLEW QUIETIO [get_ports {led[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:48
set_false_path -through [get_nets {led[8]}]
set_property PACKAGE_PIN L19 [get_ports {led[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:48
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[8]' has been applied to the port object 'led[8]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:48
# The conversion of 'DRIVE' constraint on 'net' object 'led[8]' has been applied to the port object 'led[8]'.
set_property DRIVE 2 [get_ports {led[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:48
# The conversion of 'SLEW' constraint on 'net' object 'led[8]' has been applied to the port object 'led[8]'.
set_property SLEW QUIETIO [get_ports {led[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:49
set_false_path -through [get_nets {led[7]}]
set_property PACKAGE_PIN K18 [get_ports {led[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:49
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[7]' has been applied to the port object 'led[7]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:49
# The conversion of 'DRIVE' constraint on 'net' object 'led[7]' has been applied to the port object 'led[7]'.
set_property DRIVE 2 [get_ports {led[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:49
# The conversion of 'SLEW' constraint on 'net' object 'led[7]' has been applied to the port object 'led[7]'.
set_property SLEW QUIETIO [get_ports {led[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:50
set_false_path -through [get_nets {led[6]}]
set_property PACKAGE_PIN H19 [get_ports {led[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:50
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[6]' has been applied to the port object 'led[6]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:50
# The conversion of 'DRIVE' constraint on 'net' object 'led[6]' has been applied to the port object 'led[6]'.
set_property DRIVE 2 [get_ports {led[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:50
# The conversion of 'SLEW' constraint on 'net' object 'led[6]' has been applied to the port object 'led[6]'.
set_property SLEW QUIETIO [get_ports {led[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:51
set_false_path -through [get_nets {led[5]}]
set_property PACKAGE_PIN K15 [get_ports {led[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[5]' has been applied to the port object 'led[5]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:51
# The conversion of 'DRIVE' constraint on 'net' object 'led[5]' has been applied to the port object 'led[5]'.
set_property DRIVE 2 [get_ports {led[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:51
# The conversion of 'SLEW' constraint on 'net' object 'led[5]' has been applied to the port object 'led[5]'.
set_property SLEW QUIETIO [get_ports {led[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:52
set_false_path -through [get_nets {led[4]}]
set_property PACKAGE_PIN P16 [get_ports {led[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:52
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[4]' has been applied to the port object 'led[4]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:52
# The conversion of 'DRIVE' constraint on 'net' object 'led[4]' has been applied to the port object 'led[4]'.
set_property DRIVE 2 [get_ports {led[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:52
# The conversion of 'SLEW' constraint on 'net' object 'led[4]' has been applied to the port object 'led[4]'.
set_property SLEW QUIETIO [get_ports {led[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:53
set_false_path -through [get_nets {led[3]}]
set_property PACKAGE_PIN T19 [get_ports {led[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[3]' has been applied to the port object 'led[3]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:53
# The conversion of 'DRIVE' constraint on 'net' object 'led[3]' has been applied to the port object 'led[3]'.
set_property DRIVE 2 [get_ports {led[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:53
# The conversion of 'SLEW' constraint on 'net' object 'led[3]' has been applied to the port object 'led[3]'.
set_property SLEW QUIETIO [get_ports {led[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:54
set_false_path -through [get_nets {led[2]}]
set_property PACKAGE_PIN T18 [get_ports {led[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:54
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[2]' has been applied to the port object 'led[2]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:54
# The conversion of 'DRIVE' constraint on 'net' object 'led[2]' has been applied to the port object 'led[2]'.
set_property DRIVE 2 [get_ports {led[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:54
# The conversion of 'SLEW' constraint on 'net' object 'led[2]' has been applied to the port object 'led[2]'.
set_property SLEW QUIETIO [get_ports {led[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:55
set_false_path -through [get_nets {led[1]}]
set_property PACKAGE_PIN H12 [get_ports {led[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:55
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[1]' has been applied to the port object 'led[1]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:55
# The conversion of 'DRIVE' constraint on 'net' object 'led[1]' has been applied to the port object 'led[1]'.
set_property DRIVE 2 [get_ports {led[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:55
# The conversion of 'SLEW' constraint on 'net' object 'led[1]' has been applied to the port object 'led[1]'.
set_property SLEW QUIETIO [get_ports {led[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:56
set_false_path -through [get_nets {led[0]}]
set_property PACKAGE_PIN H11 [get_ports {led[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:56
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[0]' has been applied to the port object 'led[0]'.
set_property IOSTANDARD LVCMOS25 [get_ports {led[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:56
# The conversion of 'DRIVE' constraint on 'net' object 'led[0]' has been applied to the port object 'led[0]'.
set_property DRIVE 2 [get_ports {led[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:56
# The conversion of 'SLEW' constraint on 'net' object 'led[0]' has been applied to the port object 'led[0]'.
set_property SLEW QUIETIO [get_ports {led[0]}]

########
# GPIO #
########
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:61
set_false_path -through [get_nets gpio_startn]
set_property PACKAGE_PIN D19 [get_ports gpio_startn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:61
# The conversion of 'IOSTANDARD' constraint on 'net' object 'gpio_startn' has been applied to the port object 'gpio_startn'.
set_property IOSTANDARD LVCMOS25 [get_ports gpio_startn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:61
# The conversion of 'DRIVE' constraint on 'net' object 'gpio_startn' has been applied to the port object 'gpio_startn'.
set_property DRIVE 2 [get_ports gpio_startn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:61
# The conversion of 'SLEW' constraint on 'net' object 'gpio_startn' has been applied to the port object 'gpio_startn'.
set_property SLEW QUIETIO [get_ports gpio_startn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:62
set_false_path -through [get_nets gpio_endn]
set_property PACKAGE_PIN N17 [get_ports gpio_endn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:62
# The conversion of 'IOSTANDARD' constraint on 'net' object 'gpio_endn' has been applied to the port object 'gpio_endn'.
set_property IOSTANDARD LVCMOS25 [get_ports gpio_endn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:62
# The conversion of 'DRIVE' constraint on 'net' object 'gpio_endn' has been applied to the port object 'gpio_endn'.
set_property DRIVE 2 [get_ports gpio_endn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:62
# The conversion of 'SLEW' constraint on 'net' object 'gpio_endn' has been applied to the port object 'gpio_endn'.
set_property SLEW QUIETIO [get_ports gpio_endn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:63
set_false_path -through [get_nets gpio_exec]
set_property PACKAGE_PIN N16 [get_ports gpio_exec]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:63
# The conversion of 'IOSTANDARD' constraint on 'net' object 'gpio_exec' has been applied to the port object 'gpio_exec'.
set_property IOSTANDARD LVCMOS25 [get_ports gpio_exec]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:63
# The conversion of 'DRIVE' constraint on 'net' object 'gpio_exec' has been applied to the port object 'gpio_exec'.
set_property DRIVE 2 [get_ports gpio_exec]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:63
# The conversion of 'SLEW' constraint on 'net' object 'gpio_exec' has been applied to the port object 'gpio_exec'.
set_property SLEW QUIETIO [get_ports gpio_exec]

#------------------------------------------------ Local bus
#############################################
# Spartan-6 HPIC (LVCMOS15, SSTL15 or HTSL) #
#############################################
set_property PACKAGE_PIN AB11 [get_ports lbus_clkn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:69
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_clkn' has been applied to the port object 'lbus_clkn'.
set_property IOSTANDARD LVCMOS15 [get_ports lbus_clkn]
set_property PACKAGE_PIN AA13 [get_ports lbus_rstn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:70
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_rstn' has been applied to the port object 'lbus_rstn'.
set_property IOSTANDARD LVCMOS15 [get_ports lbus_rstn]

set_property PACKAGE_PIN V4 [get_ports {lbus_do[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:72
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[0]' has been applied to the port object 'lbus_do[0]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:72
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[0]' has been applied to the port object 'lbus_do[0]'.
set_property DRIVE 2 [get_ports {lbus_do[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:72
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[0]' has been applied to the port object 'lbus_do[0]'.
set_property SLEW QUIETIO [get_ports {lbus_do[0]}]
set_property PACKAGE_PIN V2 [get_ports {lbus_do[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:73
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[1]' has been applied to the port object 'lbus_do[1]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:73
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[1]' has been applied to the port object 'lbus_do[1]'.
set_property DRIVE 2 [get_ports {lbus_do[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:73
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[1]' has been applied to the port object 'lbus_do[1]'.
set_property SLEW QUIETIO [get_ports {lbus_do[1]}]
set_property PACKAGE_PIN W1 [get_ports {lbus_do[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:74
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[2]' has been applied to the port object 'lbus_do[2]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:74
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[2]' has been applied to the port object 'lbus_do[2]'.
set_property DRIVE 2 [get_ports {lbus_do[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:74
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[2]' has been applied to the port object 'lbus_do[2]'.
set_property SLEW QUIETIO [get_ports {lbus_do[2]}]
set_property PACKAGE_PIN AB1 [get_ports {lbus_do[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:75
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[3]' has been applied to the port object 'lbus_do[3]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:75
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[3]' has been applied to the port object 'lbus_do[3]'.
set_property DRIVE 2 [get_ports {lbus_do[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:75
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[3]' has been applied to the port object 'lbus_do[3]'.
set_property SLEW QUIETIO [get_ports {lbus_do[3]}]
set_property PACKAGE_PIN Y3 [get_ports {lbus_do[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:76
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[4]' has been applied to the port object 'lbus_do[4]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:76
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[4]' has been applied to the port object 'lbus_do[4]'.
set_property DRIVE 2 [get_ports {lbus_do[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:76
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[4]' has been applied to the port object 'lbus_do[4]'.
set_property SLEW QUIETIO [get_ports {lbus_do[4]}]
set_property PACKAGE_PIN U7 [get_ports {lbus_do[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:77
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[5]' has been applied to the port object 'lbus_do[5]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:77
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[5]' has been applied to the port object 'lbus_do[5]'.
set_property DRIVE 2 [get_ports {lbus_do[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:77
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[5]' has been applied to the port object 'lbus_do[5]'.
set_property SLEW QUIETIO [get_ports {lbus_do[5]}]
set_property PACKAGE_PIN V3 [get_ports {lbus_do[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:78
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[6]' has been applied to the port object 'lbus_do[6]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:78
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[6]' has been applied to the port object 'lbus_do[6]'.
set_property DRIVE 2 [get_ports {lbus_do[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:78
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[6]' has been applied to the port object 'lbus_do[6]'.
set_property SLEW QUIETIO [get_ports {lbus_do[6]}]
set_property PACKAGE_PIN AF10 [get_ports {lbus_do[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:79
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[7]' has been applied to the port object 'lbus_do[7]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:79
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[7]' has been applied to the port object 'lbus_do[7]'.
set_property DRIVE 2 [get_ports {lbus_do[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:79
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[7]' has been applied to the port object 'lbus_do[7]'.
set_property SLEW QUIETIO [get_ports {lbus_do[7]}]
set_property PACKAGE_PIN AC13 [get_ports {lbus_do[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:80
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[8]' has been applied to the port object 'lbus_do[8]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:80
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[8]' has been applied to the port object 'lbus_do[8]'.
set_property DRIVE 2 [get_ports {lbus_do[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:80
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[8]' has been applied to the port object 'lbus_do[8]'.
set_property SLEW QUIETIO [get_ports {lbus_do[8]}]
set_property PACKAGE_PIN AE12 [get_ports {lbus_do[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:81
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[9]' has been applied to the port object 'lbus_do[9]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:81
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[9]' has been applied to the port object 'lbus_do[9]'.
set_property DRIVE 2 [get_ports {lbus_do[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:81
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[9]' has been applied to the port object 'lbus_do[9]'.
set_property SLEW QUIETIO [get_ports {lbus_do[9]}]
set_property PACKAGE_PIN U6 [get_ports {lbus_do[10]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:82
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[10]' has been applied to the port object 'lbus_do[10]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[10]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:82
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[10]' has been applied to the port object 'lbus_do[10]'.
set_property DRIVE 2 [get_ports {lbus_do[10]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:82
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[10]' has been applied to the port object 'lbus_do[10]'.
set_property SLEW QUIETIO [get_ports {lbus_do[10]}]
set_property PACKAGE_PIN AE13 [get_ports {lbus_do[11]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:83
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[11]' has been applied to the port object 'lbus_do[11]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[11]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:83
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[11]' has been applied to the port object 'lbus_do[11]'.
set_property DRIVE 2 [get_ports {lbus_do[11]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:83
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[11]' has been applied to the port object 'lbus_do[11]'.
set_property SLEW QUIETIO [get_ports {lbus_do[11]}]
set_property PACKAGE_PIN AA10 [get_ports {lbus_do[12]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:84
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[12]' has been applied to the port object 'lbus_do[12]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[12]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:84
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[12]' has been applied to the port object 'lbus_do[12]'.
set_property DRIVE 2 [get_ports {lbus_do[12]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:84
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[12]' has been applied to the port object 'lbus_do[12]'.
set_property SLEW QUIETIO [get_ports {lbus_do[12]}]
set_property PACKAGE_PIN AB12 [get_ports {lbus_do[13]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:85
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[13]' has been applied to the port object 'lbus_do[13]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[13]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:85
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[13]' has been applied to the port object 'lbus_do[13]'.
set_property DRIVE 2 [get_ports {lbus_do[13]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:85
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[13]' has been applied to the port object 'lbus_do[13]'.
set_property SLEW QUIETIO [get_ports {lbus_do[13]}]
set_property PACKAGE_PIN AA4 [get_ports {lbus_do[14]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:86
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[14]' has been applied to the port object 'lbus_do[14]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[14]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:86
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[14]' has been applied to the port object 'lbus_do[14]'.
set_property DRIVE 2 [get_ports {lbus_do[14]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:86
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[14]' has been applied to the port object 'lbus_do[14]'.
set_property SLEW QUIETIO [get_ports {lbus_do[14]}]
set_property PACKAGE_PIN AE8 [get_ports {lbus_do[15]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:87
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_do[15]' has been applied to the port object 'lbus_do[15]'.
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[15]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:87
# The conversion of 'DRIVE' constraint on 'net' object 'lbus_do[15]' has been applied to the port object 'lbus_do[15]'.
set_property DRIVE 2 [get_ports {lbus_do[15]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:87
# The conversion of 'SLEW' constraint on 'net' object 'lbus_do[15]' has been applied to the port object 'lbus_do[15]'.
set_property SLEW QUIETIO [get_ports {lbus_do[15]}]
set_property PACKAGE_PIN AD10 [get_ports lbus_wrn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_wrn' has been applied to the port object 'lbus_wrn'.
set_property IOSTANDARD LVCMOS15 [get_ports lbus_wrn]
set_property PACKAGE_PIN Y13 [get_ports lbus_rdn]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:89
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_rdn' has been applied to the port object 'lbus_rdn'.
set_property IOSTANDARD LVCMOS15 [get_ports lbus_rdn]

########################################
# Spartan-6 HRIC (LVCMOS25 or LVDS_25) #
########################################
set_property PACKAGE_PIN T22 [get_ports {lbus_di_a[0]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:94
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[0]' has been applied to the port object 'lbus_di_a[0]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[0]}]
set_property PACKAGE_PIN M24 [get_ports {lbus_di_a[1]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:95
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[1]' has been applied to the port object 'lbus_di_a[1]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[1]}]
set_property PACKAGE_PIN K25 [get_ports {lbus_di_a[2]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:96
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[2]' has been applied to the port object 'lbus_di_a[2]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[2]}]
set_property PACKAGE_PIN R26 [get_ports {lbus_di_a[3]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:97
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[3]' has been applied to the port object 'lbus_di_a[3]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[3]}]
set_property PACKAGE_PIN M25 [get_ports {lbus_di_a[4]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:98
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[4]' has been applied to the port object 'lbus_di_a[4]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[4]}]
set_property PACKAGE_PIN U17 [get_ports {lbus_di_a[5]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:99
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[5]' has been applied to the port object 'lbus_di_a[5]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[5]}]
set_property PACKAGE_PIN N26 [get_ports {lbus_di_a[6]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:100
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[6]' has been applied to the port object 'lbus_di_a[6]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[6]}]
set_property PACKAGE_PIN R16 [get_ports {lbus_di_a[7]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[7]' has been applied to the port object 'lbus_di_a[7]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[7]}]
set_property PACKAGE_PIN T20 [get_ports {lbus_di_a[8]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[8]' has been applied to the port object 'lbus_di_a[8]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[8]}]
set_property PACKAGE_PIN R22 [get_ports {lbus_di_a[9]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[9]' has been applied to the port object 'lbus_di_a[9]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[9]}]
set_property PACKAGE_PIN M21 [get_ports {lbus_di_a[10]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:104
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[10]' has been applied to the port object 'lbus_di_a[10]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[10]}]
set_property PACKAGE_PIN T24 [get_ports {lbus_di_a[11]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:105
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[11]' has been applied to the port object 'lbus_di_a[11]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[11]}]
set_property PACKAGE_PIN P23 [get_ports {lbus_di_a[12]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[12]' has been applied to the port object 'lbus_di_a[12]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[12]}]
set_property PACKAGE_PIN N21 [get_ports {lbus_di_a[13]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:107
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[13]' has been applied to the port object 'lbus_di_a[13]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[13]}]
set_property PACKAGE_PIN R21 [get_ports {lbus_di_a[14]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:108
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[14]' has been applied to the port object 'lbus_di_a[14]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[14]}]
set_property PACKAGE_PIN N18 [get_ports {lbus_di_a[15]}]
# C:/Users/mmajumde/Documents/sasebo_giii/sasebo_giii_aes/AES_crypto/const_AES.ucf:109
# The conversion of 'IOSTANDARD' constraint on 'net' object 'lbus_di_a[15]' has been applied to the port object 'lbus_di_a[15]'.
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[15]}]
